### ISSUE TITLE
A way of displaying images in the documentation

### ISSUE THREAD

**Issue by Pegacraft** [Mc-Zen/typst-doc#2]
I wanted to add an image to the documentation, but got the error `cannot access file system from here`. I'm sorry if I overlooked a possibility to already do that, but if not, I think adding it would be awesome.

**Comment by Mc-Zen** [comment]
Hi @Pegacraft ,
I don't think you overlooked something, this is currently not possible. The function descriptions are parsed as Typst code using `eval()` but as documented here

https://typst.app/docs/reference/foundations/eval/,

from within `eval()`, access to the file system is not possible :(

It is of course luxury to have most of Typsts formatting and syntax available in documentation strings just like that but the `eval()` approach has some limitations, this being one of them. 

But actually I think, I found a workaround for that. I will notify you here, once it works :)

**Comment by Mc-Zen** [comment]
It works now! You can use `image()` (or `#image()`) anywhere in function and parameter descriptions. You might want to specify absolute paths (i.e.. `/myfile.svg` instead of `myfile.svg`) for images.

**Comment by Mc-Zen** [comment]
Also look at the example in 
https://github.com/Mc-Zen/typst-doc/blob/5c4695c6bee3167807880e4350dce0c29b1a8f09/examples/funny-math/funny-math.typ#L3-L8

**Comment by Pegacraft** [comment]
Awesome ^^ Thank you so much <3

**Comment by Mc-Zen** [comment]
Your welcome!

Btw, I checked out your typst-plotting package. This is amazing and I'm totally going to use this!
